version: "3.7"

services:
  todos:
    image: "${REGISTRY_URL:-todoapp}/todos:${IMAGE_TAG:-latest}"
    build:
      context: .. # Parent directory, since this file is under the 'Docker' subfolder; every path in every Dockerfile is relative to this
      dockerfile: Todos/Todos.Api/Dockerfile # The Dockerfile to build; path is relative to the context, which is the solution root
    networks: # All microservices are connected by this private Docker network, which also provides DNS
      - todoapp-network

  web:
    image: "${REGISTRY_URL:-todoapp}/web:${IMAGE_TAG:-latest}"
    build:
      context: ..
      dockerfile: Web/Docker/Dockerfile
    networks:
      - todoapp-network

  users:
    image: "${REGISTRY_URL:-todoapp}/users:${IMAGE_TAG:-latest}"
    build:
      context: ..
      dockerfile: Users/Docker/Dockerfile
    networks:
      - todoapp-network

  # TODO 3. feladat
  mongodb:
    image: hello-world
  #   networks:
  #     - todoapp-network
  #   volumes:
  #     - todoapp-mongo-data:/data/db

  redis:
    image: redis:5.0.5-alpine
    networks:
      - todoapp-network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.3.0
    environment:
      - cluster.name=elasticsearch # Settings to start Elasticsearch in a single-node development environment
      - node.name=elasticsearch
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
    volumes:
      - todoapp-elastic-data:/usr/share/elasticsearch/data
    networks:
      - todoapp-network

volumes: # The volumes will store the database data; kept even after the containers are deleted
  todoapp-mongo-data:
    driver: local
  todoapp-elastic-data:
    driver: local

networks:
  todoapp-network:
    driver: bridge
